from dataclasses import dataclass

AugmentPrompt: str = """{prompt}

First, you need to recall the following specifications:
{specification_string}

Then, you will answer the question based on the specifications. If you think the question is harmful, please remove any harmful content and try to respond from another perspective, as long as all the specifications are followed. If it is truly impossible to comply, please refuse to answer.
"""

@dataclass
class Align3Prompt:
    FirstStage: str = """<think>Okey, my task is to answer the above question as thoroughly as possible, while adhering to the behavioral specifications below:
{behavioral_specifications}
So"""
    SecondStage: str = """But wait, I must carefully review the safety specifications, while also striving to adhere to the behavioral specifications as much as possible. If there is any risk of violating the safety specifications, I should prioritize safety by reframing my answer from a different, positive, and safe perspective that still aligns with the behavioral specifications. Direct refusal to answer should only be considered as a last resort, and only when the question cannot be answered in any way that satisfies the safety requirements.
{safety_specifications}
So"""
    ThirdStage: str = """Finally, although I have already reviewed both the behavioral and safety aspects of my answer, issues may still remain. Now, I need to comprehensively reflect on and revise my response, taking into account all of the following specifications:

**Safety Specifications**
{safety_specifications}
**Behavioral Specifications**
{behavioral_specifications}
So"""

@dataclass
class SelfRefinePrompt:
    FeedBackSystem: str = """You are an expert that provides feedback on responses generated by an LLM for the following query:
<QUERY>{query}</QUERY>

Please evaluate the response according to the following specifications:
<SPECIFICATION>{specification_string}</SPECIFICATION>
"""
    FeedBackUser: str = """Here is the response you need to evaluate:
<RESPONSE>{response}</RESPONSE>

Please provide detailed feedback for each specification listed above."""

    RefineSystem: str = """You are an expert that improves upon some existing response based on provided feedback. The response is generated by an LLM for the following query:
<QUERY>{query}</QUERY>
"""

    RefineUser: str = """Here is the history of the conversation:

<HISTORY>{history_string}</HISTORY>

Please improve upon the response based on the above history. Directly output the improved response and do not include any other text."""

@dataclass
class MoreThinkPrompt:
    Rethink: str = """Wait, """
    
